### ISSUE TITLE
glob.glob got an unexpected keyword argument 'root_dir'

### ISSUE THREAD

**Issue by studentz** [gagolews/clustering-benchmarks#3]
Set Up:

Ubuntu 20.04
Python: 3.8
The error is for both functions (get_dataset_names, get_battery_names)
Solution: Modifying get_names.py file works for me.

- get_dataset_names

`    datasets = natsorted([
        f[:-8]
        for f in glob.glob(os.path.join(path, battery, "*.data.gz"))        
        if not f.startswith(".")
    ])`

- get_battery_names
`  batteries = natsorted([
        f
        for f in glob.glob(os.path.join(path,"*"))
        if os.path.isdir(f)
    ])`

Thanks, for the project.

**Comment by gagolews** [comment]
Thanks for spotting this;

In https://docs.python.org/3/library/glob.html I read that `glob.glob` gained the `root_dir` and `dir_fd` parameters in Python 3.10.
