### ISSUE TITLE
Cant import clustbench

### ISSUE THREAD

**Issue by prabhant** [gagolews/clustering-benchmarks#4]
```python
import clustbench
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_4231/2910377517.py in <module>
      1 import os.path
----> 2 import clustbench
      3 data_path = os.path.join("~", "", "clustering-data-v1")

~/opt/anaconda3/envs/env/lib/python3.8/site-packages/clustbench/__init__.py in <module>
     30 from .load_results import transpose_results, labels_list_to_dict
     31 from .preprocess_data import preprocess_data
---> 32 from .colouriser import Colouriser
     33 from .fit_predict import fit_predict_many
     34 from .score import get_score

~/opt/anaconda3/envs/env/lib/python3.8/site-packages/clustbench/colouriser.py in <module>
     33 import numpy as np
     34 import scipy.spatial
---> 35 import genieclust
     36 
     37 

~/opt/anaconda3/envs/env/lib/python3.8/site-packages/genieclust/__init__.py in <module>
     25 
     26 
---> 27 from . import plots
     28 from . import inequity
     29 from . import tools

~/opt/anaconda3/envs/env/lib/python3.8/site-packages/genieclust/plots.py in <module>
     31 # module globals:
     32 col = ["#000000", "#DF536B", "#61D04F", "#2297E6", "#28E2E5", "#CD0BBC", "#F5C710"] + \
---> 33     [matplotlib.colors.to_hex(c) for c in plt.colormaps["tab10"].colors]  + \
     34     [matplotlib.colors.to_hex(c) for c in plt.colormaps["tab20"].colors]  + \
     35     [matplotlib.colors.to_hex(c) for c in plt.colormaps["tab20b"].colors] + \

TypeError: 'function' object is not subscriptable


```

**Comment by prabhant** [comment]
Looks like its only issue with M1, not with colab or ubuntu

**Comment by gagolews** [comment]
Which version of *matplotlib* are you using there? I suggest you update this package first.

**Comment by takatoshilee** [comment]
I'm facing the same issue. I'm on Mac M2. I've also tried moving it to google collab and updated matplotlib as well. 
On google collab:
AttributeError                            Traceback (most recent call last)
[<ipython-input-2-572702c33aa3>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import clustbench
      2 import os.path

1 frames
[/usr/local/lib/python3.10/dist-packages/clustbench/score.py](https://localhost:8080/#) in <module>
     31     labels,
     32     results,
---> 33     metric=genieclust.compare_partitions.adjusted_asymmetric_accuracy,
     34     compute_max=True,
     35     warn_if_missing=True

AttributeError: module 'genieclust.compare_partitions' has no attribute 'adjusted_asymmetric_accuracy'


On terminal:
>>> import clustbench

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniforge/base/envs/older_python_env/lib/python3.9/site-packages/clustbench/__init__.py", line 34, in <module>
    from .score import get_score
  File "/opt/homebrew/Caskroom/miniforge/base/envs/older_python_env/lib/python3.9/site-packages/clustbench/score.py", line 33, in <module>
    metric=genieclust.compare_partitions.adjusted_asymmetric_accuracy,
AttributeError: module 'genieclust.compare_partitions' has no attribute 'adjusted_asymmetric_accuracy'

**Comment by gagolews** [comment]
After a recent update (see CHANGELOG), this function was renamed -> normalised_clustering_accuracy.

**Comment by gagolews** [comment]
After a recent update to genieclust (see its CHANGELOG), this function was renamed -> please pass `metric=genieclust.compare_partitions.normalized_clustering_accuracy`. I will fix this soon and update the `clustbench` package on PyPI to reflect that.

**Comment by gagolews** [comment]
Fixed, please update the package via PyPI

**Comment by takatoshilee** [comment]
Thank you
